#!/usr/bin/env bash
#
# Regenerate the symbol-rename header for one vendored LMDB stream.
#
# Both LMDB streams are compiled into every build, so every extern symbol of a
# vendored engine must be renamed (mdb_* -> mdb09_* / mdb10_*) to avoid
# duplicate-symbol collisions -- both between the two streams and with the v1
# lmdb-go module, which links an unprefixed liblmdb (v1 and v2 must be
# co-importable in one binary).
#
# The symbol list is derived from `nm` output of a standalone compile of the
# stream's pristine sources, so it stays correct across LMDB updates. Any
# defined global that does not start with mdb_ is an error: it could not be
# renamed by this scheme and would leak into the global namespace.
#
# Globals that only exist in Windows builds (#ifdef _WIN32) are invisible to
# a compile on the unix host, so they come from an explicit win_syms list.
# When a mingw-w64 cross compiler is installed, that list is verified against
# a real Windows compile; otherwise it is trusted as-is.
#
# Usage: scripts/gen-rename.sh <09|10>
# Reads:  lmdb/{mdb,midl}_lmdbNN.c (prepended lines are stripped),
#         lmdb/{lmdb,midl}_lmdbNN.h
# Writes: lmdb/rename_lmdbNN.h

set -euo pipefail
cd "$(dirname "$0")/.."

stream="${1:-}"
case "$stream" in
    09) streamnum=9 ;;
    10) streamnum=10 ;;
    *) echo "USAGE: $0 <09|10>" >&2; exit 1 ;;
esac

src_mdb="lmdb/mdb_lmdb${stream}.c"
src_midl="lmdb/midl_lmdb${stream}.c"
hdr_lmdb="lmdb/lmdb_lmdb${stream}.h"
hdr_midl="lmdb/midl_lmdb${stream}.h"
out="lmdb/rename_lmdb${stream}.h"

for f in "$src_mdb" "$src_midl" "$hdr_lmdb" "$hdr_midl"; do
    [ -f "$f" ] || { echo "ERROR: missing $f" >&2; exit 1; }
done

get_define() { grep "^#define $1" "$hdr_lmdb" | head -1 | awk '{print $3}'; }
version="$(get_define MDB_VERSION_MAJOR).$(get_define MDB_VERSION_MINOR).$(get_define MDB_VERSION_PATCH)"

tmp="$(mktemp -d "${TMPDIR:-/tmp}/lmdbgo-rename.XXXXXX")"
trap 'rm -rf "$tmp"' EXIT

# Reconstruct the pristine upstream sources: drop only the mechanically
# prepended lines (//go:build constraint, rename include, and their blank
# separators) from the top of the vendored files.
strip_prepends() {
    awk '
        !body && NR <= 6 && (/^\/\/go:build / || /^#include "rename_lmdb/ || /^$/) { next }
        { body = 1; print }
    ' "$1"
}

strip_prepends "$src_mdb" > "$tmp/mdb.c"
strip_prepends "$src_midl" > "$tmp/midl.c"
# The pristine sources include "lmdb.h"/"midl.h"; resolve those to this
# stream's own pristine headers, independent of the package shim headers.
cp "$hdr_lmdb" "$tmp/lmdb.h"
cp "$hdr_midl" "$tmp/midl.h"

cc -c -O0 -w -o "$tmp/mdb.o" "$tmp/mdb.c"
cc -c -O0 -w -o "$tmp/midl.o" "$tmp/midl.c"

# Defined global symbols (text/data/bss/common), leading underscore stripped
# (darwin). Undefined (U) references are naturally excluded.
syms="$(nm -g "$tmp/mdb.o" "$tmp/midl.o" 2>/dev/null \
    | awk '$2 ~ /^[TDBSRC]$/ { print $3 }' \
    | sed 's/^_//' \
    | sort -u)"

[ -n "$syms" ] || { echo "ERROR: no global symbols found" >&2; exit 1; }

# Windows-only extern globals (see the header comment). mdb_tls_cbp is the
# TLS-callback registration both engines define under #ifdef _WIN32.
win_syms="mdb_tls_cbp"

mingw_cc="x86_64-w64-mingw32-gcc"
mingw_nm="x86_64-w64-mingw32-nm"
if command -v "$mingw_cc" >/dev/null && command -v "$mingw_nm" >/dev/null; then
    "$mingw_cc" -c -O0 -w -o "$tmp/mdb-win.o" "$tmp/mdb.c"
    "$mingw_cc" -c -O0 -w -o "$tmp/midl-win.o" "$tmp/midl.c"
    # .refptr.* are mingw-generated comdat stubs that follow their target
    # symbol's (renamed) name automatically; they never need renaming.
    actual_win="$("$mingw_nm" -g "$tmp/mdb-win.o" "$tmp/midl-win.o" 2>/dev/null \
        | awk 'NF >= 3 && $2 != "U" && $3 !~ /^\./ { print $3 }' \
        | sort -u)"
    uncovered="$(comm -23 <(printf '%s\n' "$actual_win") \
        <(printf '%s\n' "$syms" "$win_syms" | sort -u))"
    if [ -n "$uncovered" ]; then
        echo "ERROR: Windows build defines globals not covered by the rename list:" >&2
        printf '%s\n' "$uncovered" >&2
        echo "Add them to win_syms in $0." >&2
        exit 1
    fi
else
    echo "NOTE: no mingw-w64 cross compiler found; trusting win_syms as-is."
fi

syms="$(printf '%s\n' "$syms" "$win_syms" | sort -u)"

bad="$(printf '%s\n' "$syms" | grep -v '^mdb_' || true)"
if [ -n "$bad" ]; then
    echo "ERROR: defined globals without mdb_ prefix (cannot be renamed):" >&2
    printf '%s\n' "$bad" >&2
    exit 1
fi

{
    printf '/* GENERATED by scripts/gen-rename.sh for LMDB stream %s (LMDB %s).\n' "$stream" "$version"
    printf ' * Renames every extern symbol of the vendored engine so both streams\n'
    printf ' * can live in one binary (alongside lmdb-go v1). Do not edit by hand. */\n'
    printf '#ifndef LMDBGO_RENAME%s_H\n' "$stream"
    printf '#define LMDBGO_RENAME%s_H\n' "$stream"
    printf '#define LMDBGO_STREAM %s\n' "$streamnum"
    printf '%s\n' "$syms" | while IFS= read -r s; do
        printf '#define %s mdb%s_%s\n' "$s" "$stream" "${s#mdb_}"
    done
    printf '#endif\n'
} > "$out"

count="$(printf '%s\n' "$syms" | wc -l | tr -d ' ')"
echo "Wrote $out: $count symbols renamed to mdb${stream}_* (LMDB $version)"
